"""Added errors and created_count fields to ImportJob model

Revision ID: 2dfe42d28cf7
Revises: dd63e709e6d6
Create Date: 2026-08-26 14:23:10.610575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dfe42d28cf7'
down_revision: Union[str, Sequence[str], None] = 'dd63e709e6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('created_count', sa.Integer(), nullable=False))
    op.add_column('import_jobs', sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'errors')
    op.drop_column('import_jobs', 'created_count')
    # ### end Alembic commands ###
