"""Added is_uploaded flag to Attachment model

Revision ID: 58e93ab8fc36
Revises: dd5986b1c093
Create Date: 2026-08-17 17:17:40.269501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e93ab8fc36'
down_revision: Union[str, Sequence[str], None] = 'dd5986b1c093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('is_uploaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'is_uploaded')
    # ### end Alembic commands ###
