"""Added format field to ExportJob

Revision ID: 5a6f0f4f40aa
Revises: 4b9f5ad6d550
Create Date: 2026-09-02 18:27:35.326750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6f0f4f40aa'
down_revision: Union[str, Sequence[str], None] = '4b9f5ad6d550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'format')
    # ### end Alembic commands ###
