"""Added role to model User

Revision ID: 7178301218e9
Revises: f1544026c980
Create Date: 2026-07-22 00:01:44.488173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '7178301218e9'
down_revision: Union[str, Sequence[str], None] = 'f1544026c980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = ENUM('USER', 'MANAGER', 'ADMIN', name='userrole', create_type=True)
    user_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('USER', 'MANAGER', 'ADMIN', name='userrole'),
            nullable=False,
            server_default='USER',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    ENUM(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###