"""Added user_id field to model AnalyticsJob

Revision ID: 75fef9db6ff3
Revises: 95d03511e7fc
Create Date: 2026-08-25 13:19:56.955133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75fef9db6ff3'
down_revision: Union[str, Sequence[str], None] = '95d03511e7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analytics_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.execute("ALTER TYPE analyticsjobstatus RENAME TO jobstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics_jobs', type_='foreignkey')
    op.drop_column('analytics_jobs', 'user_id')

    op.execute("ALTER TYPE jobstatus RENAME TO analyticsjobstatus")
    # ### end Alembic commands ###
