"""Added time fields to ToDo

Revision ID: 812c5733f34d
Revises: f0470ef831f3
Create Date: 2026-07-12 20:06:11.987591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812c5733f34d'
down_revision: Union[str, Sequence[str], None] = 'f0470ef831f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('todos', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
