"""Added search_vector and indexes for ToDo

Revision ID: b163c08452a6
Revises: 7178301218e9
Create Date: 2026-07-29 20:29:09.436822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b163c08452a6'
down_revision: Union[str, Sequence[str], None] = '7178301218e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')

    op.add_column('todos', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(description, '')), 'B')", persisted=True), nullable=True))
    op.create_index('idx_todo_search', 'todos', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_todo_title_trgm', 'todos', [sa.literal_column('lower(title)').label('lower_title')], unique=False, postgresql_using='gin', postgresql_ops={'lower_title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_todo_title_trgm', table_name='todos', postgresql_using='gin', postgresql_ops={'lower_title': 'gin_trgm_ops'})
    op.drop_index('idx_todo_search', table_name='todos', postgresql_using='gin')
    op.drop_column('todos', 'search_vector')

    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    # ### end Alembic commands ###
