"""Added created_at field to AnalyticsJob model

Revision ID: d030e970683a
Revises: 4f76ae0cf8b9
Create Date: 2026-08-10 20:29:14.288046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd030e970683a'
down_revision: Union[str, Sequence[str], None] = '4f76ae0cf8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_jobs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_jobs', 'created_at')
    # ### end Alembic commands ###
