"""Created ImportJob model

Revision ID: dd63e709e6d6
Revises: 75fef9db6ff3
Create Date: 2026-08-25 20:26:55.568533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.operations.toimpl import create_constraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'dd63e709e6d6'
down_revision: Union[str, Sequence[str], None] = '75fef9db6ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status', ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED', name='jobstatus', create_type=False), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
