"""Extended ToDo model: version and updated_at, timestamp

Revision ID: f1544026c980
Revises: 35e9b15aa469
Create Date: 2026-07-21 22:28:08.928063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1544026c980'
down_revision: Union[str, Sequence[str], None] = '35e9b15aa469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('todos', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('todos', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('todos', 'version')
    op.drop_column('todos', 'updated_at')
    # ### end Alembic commands ###
